### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by ttomtsis** [ttomtsis/DVDApplication#16]
Use a template to improve README and better describe project

**Comment by ebyaug007** [comment]
Hi,
While it's not exactly README.md improvement, I've added swagger for apis to this project.

If that's something you are looking for, I'm happy to make a pull request.

**Comment by ttomtsis** [comment]
> Hi, While it's not exactly README.md improvement, I've added swagger for apis to this project.
> 
> If that's something you are looking for, I'm happy to make a pull request.

Currently not interested, when i am done with some bugfixes i will check it out through.
Thank you kindly for your interest.
